import { useState, useEffect } from 'react';
import { metadataApi, predictionApi } from '../services/api';
import { RiskBadge, PredictionBadge } from '../components/RiskBadge';
import { Loader2, ArrowRight, ShieldAlert, CheckCircle, Info, Target } from 'lucide-react';
import { formatPercent } from '../utils/helpers';

export default function Predict() {
  const [districts, setDistricts] = useState([]);
  const [stages, setStages] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [result, setResult] = useState(null);

  // Form state
  const [formData, setFormData] = useState({
    project_id: '',
    district: '',
    total_land_parcels: '',
    acquired_land_parcels: '',
    total_landowners: '',
    compensation_pending: '',
    legal_cases: '0',
    documents_pending: '0',
    approval_pending_days: '0',
    objections_count: '0',
    survey_completed_percent: '100',
    current_stage: '',
    previous_delay_days: '0'
  });

  useEffect(() => {
    metadataApi.getMetadata().then(res => {
      setDistricts(res.data.districts || []);
      setStages(res.data.current_stages || []);
      if (res.data.districts?.length) setFormData(prev => ({ ...prev, district: res.data.districts[0] }));
      if (res.data.current_stages?.length) setFormData(prev => ({ ...prev, current_stage: res.data.current_stages[0] }));
    });
  }, []);

  // Auto-calculated fields
  const totalParcels = parseInt(formData.total_land_parcels) || 0;
  const acquiredParcels = parseInt(formData.acquired_land_parcels) || 0;
  const pendingParcels = Math.max(0, totalParcels - acquiredParcels);
  const pendingPercent = totalParcels > 0 ? ((pendingParcels / totalParcels) * 100).toFixed(2) : 0;

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    
    // Validation
    if (acquiredParcels > totalParcels) {
      setError('Acquired land parcels cannot exceed total land parcels.');
      return;
    }
    const compPending = parseInt(formData.compensation_pending) || 0;
    const totalOwners = parseInt(formData.total_landowners) || 1;
    if (compPending > totalOwners) {
      setError('Compensation pending cannot exceed total landowners.');
      return;
    }

    setLoading(true);
    setResult(null);

    try {
      const payload = {
        ...formData,
        project_id: formData.project_id || undefined,
        total_land_parcels: totalParcels,
        acquired_land_parcels: acquiredParcels,
        pending_land_parcels: pendingParcels,
        total_landowners: totalOwners,
        compensation_pending: compPending,
        legal_cases: parseInt(formData.legal_cases) || 0,
        documents_pending: parseInt(formData.documents_pending) || 0,
        approval_pending_days: parseInt(formData.approval_pending_days) || 0,
        objections_count: parseInt(formData.objections_count) || 0,
        survey_completed_percent: parseFloat(formData.survey_completed_percent) || 0,
        previous_delay_days: parseInt(formData.previous_delay_days) || 0,
        land_pending_percent: parseFloat(pendingPercent)
      };

      const res = await predictionApi.predict(payload);
      setResult(res.data);
      window.scrollTo({ top: 0, behavior: 'smooth' });
    } catch (err) {
      setError(err.response?.data?.detail || 'Failed to generate prediction');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      
      {result && (
        <div className="bg-card border border-border rounded-2xl shadow-xl overflow-hidden mb-8 animate-in fade-in slide-in-from-bottom-4">
          <div className="bg-slate-800/50 p-6 border-b border-border flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
            <div>
              <h2 className="text-2xl font-bold text-slate-100 flex items-center gap-3">
                <Target className="w-6 h-6 text-primary-500" />
                Prediction Result
              </h2>
              <p className="text-slate-400 mt-1">Generated by {result.model_name} {result.model_version}</p>
            </div>
            <div className="flex gap-3">
              <RiskBadge level={result.risk_level} />
              <PredictionBadge prediction={result.prediction} />
            </div>
          </div>

          <div className="p-8 grid grid-cols-1 md:grid-cols-3 gap-8">
            {/* Probability Circle */}
            <div className="flex flex-col items-center justify-center border-r border-border/50 pr-8">
              <div className="relative w-48 h-48 flex items-center justify-center">
                <svg className="w-full h-full transform -rotate-90">
                  <circle cx="96" cy="96" r="88" stroke="currentColor" strokeWidth="12" fill="transparent" className="text-slate-700" />
                  <circle 
                    cx="96" cy="96" r="88" 
                    stroke="currentColor" 
                    strokeWidth="12" 
                    fill="transparent" 
                    strokeDasharray={2 * Math.PI * 88}
                    strokeDashoffset={2 * Math.PI * 88 * (1 - result.delay_probability)}
                    className={result.prediction === 'Yes' ? 'text-red-500' : 'text-green-500'}
                    strokeLinecap="round"
                  />
                </svg>
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                  <span className="text-4xl font-bold text-slate-100">{formatPercent(result.delay_probability * 100)}</span>
                  <span className="text-xs text-slate-400 mt-1 uppercase tracking-wider">Delay Prob</span>
                </div>
              </div>
              <div className="mt-6 text-center">
                <p className="text-sm text-slate-300">
                  {result.prediction === 'Yes' 
                    ? 'This project exhibits patterns highly correlated with historical delays.' 
                    : 'This project is currently tracking within normal parameters.'}
                </p>
              </div>
            </div>

            {/* Risk Factors */}
            <div className="md:col-span-2 space-y-6">
              {result.unknown_district_warning && (
                <div className="bg-orange-500/10 border border-orange-500/20 text-orange-400 p-3 rounded-lg text-sm flex items-start gap-2">
                  <ShieldAlert className="w-5 h-5 shrink-0 mt-0.5" />
                  <p>{result.unknown_district_warning}</p>
                </div>
              )}

              <div>
                <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-3">Top Risk Factors (SHAP)</h3>
                <div className="space-y-2">
                  {result.top_risk_factors.slice(0, 5).map((f, idx) => (
                    <div key={idx} className="flex justify-between items-center p-3 rounded-lg bg-surface border border-border">
                      <div className="flex items-center gap-3">
                        {f.direction === 'increases_risk' ? (
                          <div className="w-2 h-2 rounded-full bg-red-500" />
                        ) : (
                          <div className="w-2 h-2 rounded-full bg-green-500" />
                        )}
                        <span className="font-medium text-slate-200">{f.feature}</span>
                      </div>
                      <div className="text-right">
                        <span className="text-slate-100 font-mono text-sm mr-4 bg-slate-800 px-2 py-1 rounded">Val: {f.value}</span>
                        <span className="text-slate-400 text-xs">Imp: {f.importance.toFixed(3)}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {result.recommendations.length > 0 && (
                <div>
                  <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-3">Recommended Actions</h3>
                  <div className="space-y-3">
                    {result.recommendations.map((r, idx) => (
                      <div key={idx} className="p-4 rounded-lg bg-primary-900/10 border border-primary-500/20">
                        <div className="flex items-center gap-2 mb-1">
                          <span className={`text-[10px] uppercase font-bold px-2 py-0.5 rounded-full ${
                            r.priority === 'High' ? 'bg-red-500/20 text-red-400' : 
                            r.priority === 'Medium' ? 'bg-orange-500/20 text-orange-400' : 'bg-blue-500/20 text-blue-400'
                          }`}>
                            {r.priority} Priority
                          </span>
                          <h4 className="font-semibold text-slate-200">{r.action}</h4>
                        </div>
                        <p className="text-sm text-slate-400 mt-2 pl-1 border-l-2 border-primary-500/30">{r.reason}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Input Form */}
      <div className="bg-card border border-border rounded-2xl shadow-lg overflow-hidden">
        <div className="p-6 border-b border-border">
          <h2 className="text-xl font-semibold text-slate-100">Project Information</h2>
          <p className="text-sm text-slate-400 mt-1">Enter current project parameters to run the AI prediction model.</p>
          {error && (
            <div className="mt-4 bg-red-500/10 border border-red-500/20 text-red-500 p-3 rounded-lg text-sm flex items-center gap-2">
              <ShieldAlert className="w-5 h-5" />
              {error}
            </div>
          )}
        </div>
        
        <form onSubmit={handleSubmit} className="p-6">
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-x-6 gap-y-5">
            
            {/* Core Info */}
            <div className="space-y-5 xl:col-span-3 grid grid-cols-1 md:grid-cols-3 gap-6 p-4 bg-surface rounded-xl border border-border">
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-1">Project ID (Optional)</label>
                <input type="text" name="project_id" value={formData.project_id} onChange={handleChange} className="w-full bg-card border border-border rounded-lg px-3 py-2 text-slate-200 focus:ring-1 focus:ring-primary-500 outline-none" placeholder="e.g. PRJ-2024-001" />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-1">District *</label>
                <select name="district" value={formData.district} onChange={handleChange} required className="w-full bg-card border border-border rounded-lg px-3 py-2 text-slate-200 focus:ring-1 focus:ring-primary-500 outline-none">
                  <option value="" disabled>Select District</option>
                  {districts.map(d => <option key={d} value={d}>{d}</option>)}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-1">Current Stage *</label>
                <select name="current_stage" value={formData.current_stage} onChange={handleChange} required className="w-full bg-card border border-border rounded-lg px-3 py-2 text-slate-200 focus:ring-1 focus:ring-primary-500 outline-none">
                  <option value="" disabled>Select Stage</option>
                  {stages.map(s => <option key={s} value={s}>{s}</option>)}
                </select>
              </div>
            </div>

            {/* Land Metrics */}
            <div className="col-span-1 space-y-4">
              <h3 className="text-sm font-semibold text-primary-400 uppercase tracking-wider mb-2 flex items-center gap-2"><div className="w-1.5 h-1.5 rounded-full bg-primary-500"/> Land Acquisition</h3>
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-1">Total Land Parcels *</label>
                <input type="number" name="total_land_parcels" min="1" required value={formData.total_land_parcels} onChange={handleChange} className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-slate-200 outline-none focus:border-primary-500" />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-1">Acquired Parcels *</label>
                <input type="number" name="acquired_land_parcels" min="0" required value={formData.acquired_land_parcels} onChange={handleChange} className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-slate-200 outline-none focus:border-primary-500" />
              </div>
              <div className="pt-2">
                <div className="flex justify-between text-sm text-slate-400 mb-1">
                  <span>Pending Parcels (Auto)</span>
                  <span className="font-mono text-slate-200">{pendingParcels}</span>
                </div>
                <div className="flex justify-between text-sm text-slate-400">
                  <span>Pending Area % (Auto)</span>
                  <span className="font-mono text-slate-200">{pendingPercent}%</span>
                </div>
              </div>
            </div>

            {/* Compensation & Legal */}
            <div className="col-span-1 space-y-4">
              <h3 className="text-sm font-semibold text-orange-400 uppercase tracking-wider mb-2 flex items-center gap-2"><div className="w-1.5 h-1.5 rounded-full bg-orange-500"/> Compensation & Legal</h3>
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-1">Total Landowners *</label>
                <input type="number" name="total_landowners" min="1" required value={formData.total_landowners} onChange={handleChange} className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-slate-200 outline-none focus:border-primary-500" />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-1">Compensation Pending *</label>
                <input type="number" name="compensation_pending" min="0" required value={formData.compensation_pending} onChange={handleChange} className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-slate-200 outline-none focus:border-primary-500" />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-1">Active Legal Cases *</label>
                <input type="number" name="legal_cases" min="0" required value={formData.legal_cases} onChange={handleChange} className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-slate-200 outline-none focus:border-primary-500" />
              </div>
            </div>

            {/* Admin & Process */}
            <div className="col-span-1 space-y-4">
              <h3 className="text-sm font-semibold text-green-400 uppercase tracking-wider mb-2 flex items-center gap-2"><div className="w-1.5 h-1.5 rounded-full bg-green-500"/> Administration</h3>
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-1">Approval Pending (Days) *</label>
                <input type="number" name="approval_pending_days" min="0" required value={formData.approval_pending_days} onChange={handleChange} className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-slate-200 outline-none focus:border-primary-500" />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-1">Documents Pending *</label>
                <input type="number" name="documents_pending" min="0" required value={formData.documents_pending} onChange={handleChange} className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-slate-200 outline-none focus:border-primary-500" />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-1 text-xs truncate">Objections</label>
                  <input type="number" name="objections_count" min="0" required value={formData.objections_count} onChange={handleChange} className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-slate-200 outline-none focus:border-primary-500" />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-1 text-xs truncate">Survey %</label>
                  <input type="number" name="survey_completed_percent" min="0" max="100" step="0.1" required value={formData.survey_completed_percent} onChange={handleChange} className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-slate-200 outline-none focus:border-primary-500" />
                </div>
              </div>
            </div>
            
            {/* Historical */}
            <div className="col-span-1 md:col-span-2 xl:col-span-3 mt-4 pt-6 border-t border-border">
              <div className="w-full md:w-1/3">
                <label className="block text-sm font-medium text-slate-300 mb-1 flex items-center gap-2">
                  <Info className="w-4 h-4 text-slate-500" />
                  Previous Delay Days
                </label>
                <input type="number" name="previous_delay_days" min="0" required value={formData.previous_delay_days} onChange={handleChange} className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-slate-200 outline-none focus:border-primary-500" placeholder="Historical delays if applicable" />
              </div>
            </div>

          </div>

          <div className="mt-8 flex items-center gap-4 bg-slate-900/50 -mx-6 -mb-6 p-6 border-t border-border rounded-b-2xl">
            <button 
              type="submit" 
              disabled={loading}
              className="bg-primary-600 hover:bg-primary-500 text-white font-medium rounded-lg px-6 py-2.5 flex items-center gap-2 transition-colors focus:ring-4 focus:ring-primary-500/20"
            >
              {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : <><Brain className="w-5 h-5" /> Run AI Prediction</>}
            </button>
            <p className="text-xs text-slate-500">Note: delay_status is the target variable and is strictly excluded from inputs.</p>
          </div>
        </form>
      </div>
    </div>
  );
}

import { Brain } from 'lucide-react';
